---
name: Build operator

on:
  workflow_call:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  # cancel jobs in progress for updated PRs, but not merge or tag events
  cancel-in-progress: ${{ github.event.action == 'synchronize' }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            slug: linux-amd64
            goarch: amd64
            filearch: x86-64
          - platform: linux/arm64
            slug: linux-arm64
            goarch: arm64
            filearch: aarch64
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - uses: actions/setup-go@v4
      with:
        cache-dependency-path: |
          src/go.sum
        go-version-file: src/go.mod

    - id: build
      run: |
        set -x

        wget -qO /usr/local/bin/operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-$(uname -m)-linux-gnu
        chmod +x /usr/local/bin/operator-sdk

        release_sha=$(cd src; git rev-parse HEAD)
        SECRET_OPERATOR_VERSION=${release_sha::7}

        ln -s src ${DOCKER_IMAGE}
        pushd ${DOCKER_IMAGE}
        make build
        [[ $(file -b build/_output/bin/kubernetes-secret-generator) =~ ${{ matrix.filearch }} ]]
        echo "release_sha=${release_sha}" >> $GITHUB_OUTPUT

      env:
        OPERATOR_SDK_VERSION: v0.19.1
        DOCKER_IMAGE: kubernetes-secret-generator # throw away image(s)
        DOCKER_DEFAULT_PLATFORM: ${{ matrix.platform }} # throw away image(s)
        GOARCH: ${{ matrix.goarch }}

    - run: |
        cat <src/build/_output/bin/kubernetes-secret-generator \
          | zstd > ${{ runner.temp }}/kubernetes-secret-generator.zst

    - uses: actions/upload-artifact@v3
      with:
        name: kubernetes-secret-generator-${{ steps.build.outputs.release_sha }}-${{ matrix.slug }}
        path: ${{ runner.temp }}/kubernetes-secret-generator.zst
        if-no-files-found: error
        retention-days: 1